name: "Branch Gatekeeper"
on:
  pull_request:
    branches: [ "main" ]

jobs:
  enforce-source:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check source branch
        if: github.head_ref != 'development'
        run: |
          echo "::error::Solo se permiten Pull Requests desde 'development' hacia 'main'."
          exit 1
